version: '3'
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata: