import { CreateUserModel } from '../models/create-user.model'
import { CreatedUserModel } from '../models/created-user.model'

/**
 * Description: creates a new user
 *
 * @export
 * @abstract
 * @class CreateUserFeature
 */
export abstract class CreateUserFeature {
  /**
   * Description: creates a new user with default autogenerated and returns the created user object
   *
   * @abstract
   * @param {CreateUserModel} user
   * @return {*}  {Promise<CreatedUserModel>}
   * @memberof CreateUserFeature
   */
  abstract execute(
    user: CreateUserModel,
  ): Promise<CreatedUserModel>
}
