import { CreateUserModel } from '../models/create-user.model'
import { CreatedUserModel } from '../models/created-user.model'

/**
 * Description: Protocol interface to connect with adapter layer to create a new user
 *
 * @export
 * @abstract
 * @class CreateUserProtocol
 */
export abstract class CreateUserProtocol {
  /**
   *  Description: creates a new user with default autogenerated and returns the created user object
   *
   * @abstract
   * @param {CreateUserModel} user the user to create
   * @return {*}  {Promise<CreatedUserModel>}
   * @memberof CreateUserProtocol
   */
  abstract execute(
    user: CreateUserModel
  ): Promise<CreatedUserModel>
}
